INSERT INTO CATEGORY(NAME)
    VALUES ('CAKE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Cupcake', 12, 4, 1, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Chocolate Cake', 30, 20, 0, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Pound Cake', 25, 15, 0, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Angel Cake', 22, 15, 1, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Tiramisu', 15, 5, 1, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Cheese Cake', 8, 10, 0, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Butter cake', 40, 10, 0, NULL, 1);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Babka', 50, 30, 1, NULL, 1);


INSERT INTO CATEGORY(NAME)
    VALUES ('COFFEE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Dutch Coffee', 10, 5, 0, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Cafe Mocha', 12, 15, 1, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Affogato', 22, 5, 0, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Americano', 5, 5, 1, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Espresso', 3, 5, 1, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Cappuccino', 4, 2, 0, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Mocha', 5, 3, 1, NULL, 2);

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_ID)
    VALUES ('Latte', 8, 5, 0, NULL, 2);



